'use client';

import { useEffect, useState } from 'react';
import './styles.css';

const SEARCH_LIMIT = 5;
const CONTACT_EMAIL = 'j.pranav9@gmail.com';
function initials(name) { return name.split(' ').filter(Boolean).slice(0, 2).map((part) => part[0]).join('').toUpperCase(); }
function buildConnectNote(prospect) { const firstName = prospect.name.split(' ')[0]; return `Hi ${firstName}, came across your work in ${prospect.role}. I’m exploring how AEO and AI search are changing the way marketing teams think about visibility. Thought it would be good to connect.`; }
function contactHref(subject) { return `mailto:${CONTACT_EMAIL}?subject=${encodeURIComponent(subject)}`; }

export default function Home() {
  const [company, setCompany] = useState(''); const [prospects, setProspects] = useState([]); const [searchedCompany, setSearchedCompany] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [searchesUsed, setSearchesUsed] = useState(0); const [accountEmail, setAccountEmail] = useState(''); const [savedNames, setSavedNames] = useState([]); const [savingName, setSavingName] = useState(''); const [copiedName, setCopiedName] = useState('');
  useEffect(() => { fetch('/api/usage').then(r => r.ok ? r.json() : null).then(d => { if (d) setSearchesUsed(Math.min(d.searchCount || 0, SEARCH_LIMIT)); }).catch(() => {}); fetch('/api/auth/me').then(r => r.ok ? r.json() : null).then(d => { if (d?.authenticated) setAccountEmail(d.email); }).catch(() => {}); }, []);
  async function handleSubmit(e) { e.preventDefault(); const name = company.trim(); if (!name || loading) return; if (searchesUsed >= SEARCH_LIMIT) { setError('You have used all 5 free searches.'); return; } setLoading(true); setError(''); setProspects([]); setSearchedCompany(name); try { const r = await fetch('/api/prospects', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({company:name}) }); const d = await r.json(); if (!r.ok) { if (d.limitReached) setSearchesUsed(SEARCH_LIMIT); throw new Error(d.error || 'Could not research this company.'); } setSearchesUsed(SEARCH_LIMIT - (d.remaining ?? 0)); setProspects(d.prospects || []); } catch(err) { setError(err.message || 'Something went wrong. Please try again.'); } finally { setLoading(false); } }
  async function saveProspect(prospect) { if (!accountEmail) { window.location.href='/signin'; return; } setSavingName(prospect.name); try { const r=await fetch('/api/history',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'saveProspect',company:searchedCompany,prospect})}); const d=await r.json(); if(!r.ok) throw new Error(d.error || 'Could not save prospect.'); setSavedNames(c=>c.includes(prospect.name)?c:[...c,prospect.name]); } catch(err){setError(err.message || 'Could not save this prospect.');} finally{setSavingName('');} }
  async function copyConnectNote(prospect) { try { await navigator.clipboard.writeText(buildConnectNote(prospect)); setCopiedName(prospect.name); setTimeout(()=>setCopiedName(''),2200); } catch { setError('Could not copy the connection note.'); } }
  const remaining=SEARCH_LIMIT-searchesUsed; const limitReached=searchesUsed>=SEARCH_LIMIT; const demoHref=contactHref('Book a demo - RouteProspect'); const proHref=contactHref('RouteProspect Pro');
  return <main className="page">
    <nav className="nav"><a className="brand brand-link" href="/"><img src="/routeprospect-mark.svg" alt="RouteProspect" width="38" height="38" style={{display:'block',borderRadius:'10px'}}/><span>RouteProspect</span></a><div className="nav-actions"><a className="nav-link" href="/resources">Resources</a><a className="nav-link" href="/contact">Contact</a><a className="nav-link" href={demoHref}>Book a demo</a>{accountEmail?<a className="nav-link" href="/dashboard">Workspace</a>:<a className="nav-link signin-link" href="/signin">Sign in</a>}</div></nav>
    <section className="hero"><div className="eyebrow">PROSPECT INTELLIGENCE FOR AEO/GEO PRODUCT BUILDERS</div><h1>Find the right marketing people who work on <em>AI search.</em></h1><p className="subhead">Built for founders, sales teams and marketers selling AEO/GEO products. Enter a target company and discover the marketing people most relevant to AI search — why they matter and how to approach them.</p><form className="search" onSubmit={handleSubmit}><div className="input-wrap"><label htmlFor="company">Target company</label><input id="company" value={company} onChange={e=>setCompany(e.target.value)} placeholder="e.g. HubSpot"/></div><button type="submit" disabled={loading||!company.trim()||limitReached}>{loading?'Researching…':limitReached?'Pro available':'Find Prospects'} <span>→</span></button></form><div className="hint">Try a real company: <strong>HubSpot</strong></div><div className="usage">{searchesUsed} of {SEARCH_LIMIT} free searches used · {remaining} remaining</div></section>
    {!searchedCompany&&!loading&&!limitReached&&<section className="homepage-content">
      <div className="intro-block"><div className="eyebrow">WHY THIS EXISTS</div><h2>Prospecting for AEO/GEO shouldn't mean reaching the wrong person and waiting for a reply.</h2><p>RouteProspect helps AEO/GEO sellers answer the questions that matter before outreach: who is relevant, what do they own, what evidence suggests they may care and what is a sensible reason to start the conversation?</p></div>
      <div className="use-case-grid"><article className="use-case"><span>01</span><h3>Find the right ICP</h3><p>Identify marketing people connected to SEO, content, growth, demand generation and product marketing instead of relying on title alone.</p></article><article className="use-case"><span>02</span><h3>Spot the account signal</h3><p>Use public evidence around search, content, growth and AI to understand whether the account has a reason to care.</p></article><article className="use-case"><span>03</span><h3>Know why the person matters</h3><p>See the reasoning behind each prospect so you can decide who deserves a message before you spend time personalizing it.</p></article><article className="use-case"><span>04</span><h3>Start with a useful angle</h3><p>Turn evidence into a practical conversation hypothesis instead of another generic “we help with AEO” pitch.</p></article></div>
      <div className="workflow-block"><div><div className="eyebrow">HOW IT WORKS</div><h2>Company → People → Evidence → Outreach</h2><p>Start with one company. RouteProspect researches public web evidence, identifies relevant marketing prospects and gives you context for the first conversation.</p></div><div className="workflow-steps"><div><b>01</b><span>Enter a company</span></div><div><b>02</b><span>Find relevant people</span></div><div><b>03</b><span>Understand the signals</span></div><div><b>04</b><span>Get a customized angle</span></div></div></div>
      <div className="pro-card"><div><div className="eyebrow">PRO</div><h2>Need to prospect at scale?</h2><p>Pro is for teams that want more than five searches — including bulk company upload and research, plus the full prospect intelligence workflow.</p></div><div style={{display:'flex',flexDirection:'column',alignItems:'flex-end',gap:'10px'}}><span className="pro-pill">PRO</span><a href={proHref} style={{display:'inline-flex',alignItems:'center',justifyContent:'center',padding:'10px 16px',borderRadius:'9px',background:'white',color:'var(--ink)',fontSize:'12px',fontWeight:700,textDecoration:'none'}}>Contact for Pro →</a></div></div>
      <section className="resource-preview"><div className="eyebrow">FOR AEO/GEO SDRs</div><h2>Know what to research before you send the message.</h2><p>We are building a practical knowledge base around AEO sales: ICP signals, buyer ownership, account research and outreach. These are the questions an SDR should answer before opening LinkedIn.</p><div className="resource-preview-grid"><a href="/resources/aeo-sales-prospecting"><b>AEO Sales Prospecting</b><span>Find the right ICP →</span></a><a href="/resources/aeo-sdr-playbook"><b>AEO SDR Playbook</b><span>Research before outreach →</span></a><a href="/resources/ai-search-buyers"><b>Who Buys AEO?</b><span>Map the buyer →</span></a></div><a className="resource-all" href="/resources">Explore all resources →</a></section>
    </section>}
    {loading&&<section className="empty"><div className="empty-icon">✦</div><p>Researching {searchedCompany} and finding relevant marketing people…</p></section>}
    {!loading&&error&&!limitReached&&<section className="empty"><div className="empty-icon">!</div><p>{error}</p></section>}
    {!loading&&limitReached&&<section className="empty"><div className="empty-icon">✓</div><p><strong>You’ve used all 5 free searches.</strong></p><div className="waitlist-box"><h3>Ready for more?</h3><p>Upgrade to Pro for more searches, bulk company upload and research, and the full prospect intelligence workflow.</p><div style={{display:'flex',gap:'10px',justifyContent:'center',flexWrap:'wrap',marginTop:'18px'}}><a href={proHref} style={{display:'inline-flex',alignItems:'center',justifyContent:'center',height:'42px',padding:'0 18px',borderRadius:'9px',background:'var(--ink)',color:'white',fontSize:'12px',fontWeight:700,textDecoration:'none'}}>Contact for Pro</a><a href={demoHref} style={{display:'inline-flex',alignItems:'center',justifyContent:'center',height:'42px',padding:'0 18px',borderRadius:'9px',background:'white',color:'var(--ink)',border:'1px solid var(--line)',fontSize:'12px',fontWeight:700,textDecoration:'none'}}>Book a demo</a></div></div></section>}
    {!loading&&!error&&!limitReached&&searchedCompany&&<section className="results"><div className="results-head"><div><div className="eyebrow">PROSPECTS FOUND</div><h2>Who to reach at {searchedCompany}</h2></div><span className="count">{prospects.length} relevant prospects</span></div>{prospects.length>0?<div className="cards">{prospects.map((p,i)=><article className="card" key={`${p.name}-${i}`}><div className="card-top"><div className="avatar">{initials(p.name)}</div><div><h3>{p.name}</h3><p className="role">{p.role}</p></div><span className={`priority p${i}`}>{p.confidence||'Relevant'}</span></div><div className="detail"><span>WHY THIS PERSON</span><p>{p.why}</p></div><div className="detail"><span>AEO CONTEXT</span><p>{p.relevance}</p></div><div className="angle"><span>OUTREACH ANGLE</span><p>{p.angle}</p></div><div className="card-actions"><a className="source-link" href={p.sourceUrl} target="_blank" rel="noreferrer">Open profile / evidence ↗</a><button className="save-button" type="button" onClick={()=>saveProspect(p)} disabled={savingName===p.name}>{savedNames.includes(p.name)?'Saved ✓':savingName===p.name?'Saving…':'Save prospect'}</button></div><div className="connect-row"><button className="connect-button" type="button" onClick={()=>copyConnectNote(p)}>{copiedName===p.name?'Connection note copied ✓':'Copy connection note'}</button></div></article>)}</div>:<div className="empty"><div className="empty-icon">?</div><p>No well-supported marketing prospects were found. Try the company name again.</p></div>}<p className="disclaimer">Research based on publicly available web evidence · AI-generated summaries should be verified before outreach.</p></section>}
  </main>;
}
